
# Playbook to configure the orchestration box

- name: ansible user known host
  hosts: all
  gather_facts: False
  connection: local
  roles:
    - { role: "known-hosts", known_hosts_user: "{{lookup('env', 'USER')}}" }

