
# Playbook to configure the orchestration box

- name: ansible user known host
  hosts: all
  gather_facts: False
  connection: local
  roles:
    - { role: "known-hosts", known_hosts_user: "{{lookup('env', 'USER')}}" }

- name: buildbot user
  hosts: all
  connection: local
  roles:
    - { role: "known-hosts", known_hosts_user: "buildbot" }
  pre_tasks:

  - name: add buildbot user
    delegate_to: localhost
    run_once: yes
    become: yes
    user:
      name: buildbot

  - name: deploy script
    delegate_to: localhost
    run_once: yes
    set_fact:
      deploy_script: "{{lookup('env', 'PWD')}}/scripts/deploy.sh"

  # buildbot will run, e.g.:
  # sudo -H -S -u vagrant /vagrant/ansible/scripts/deploy.sh test/vagrant_inventory $GIT_REV
  - name: Add sudoers deploy alias
    delegate_to: localhost
    run_once: yes
    become: yes
    lineinfile:
      line: "Cmnd_Alias ANSIBLE_DEPLOY = {{deploy_script}} * *"
      regexp: '^Cmnd_Alias ANSIBLE_DEPLOY'
      path: /etc/sudoers
      validate: 'visudo -cf %s'

  - name: add buildbot entry to sudoers
    delegate_to: localhost
    run_once: yes
    become: yes
    lineinfile:
      line: "buildbot ALL=({{lookup('env', 'USER')}}) NOPASSWD: ANSIBLE_DEPLOY"
      regexp: '^buildbot'
      path: /etc/sudoers
      validate: 'visudo -cf %s'

