- name: build certbot image
  delegate_to: localhost
  register: certbot_image
  docker_image:
    push: yes
    force: yes
    path: ../docker/certbot
    name: "{{docker_registry_name}}/cerbot"

- name: generate init script
  template:
    src: templates/certbot.sh.j2
    dest: "{{ansible_env.HOME}}/certbot.sh"

- name: open firewall for certbot
  with_items:
    - 80
    - 54001
  ufw:
    rule: allow
    port: "{{item}}"

- name: certbot container
  docker_container:
    image: "{{certbot_image.image['RepoDigests'][0]}}"
    name: certbot
    network_mode: host
    recreate: yes
    restart_policy: "{{docker_default_restart_policy}}"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/haproxy/certs:/etc/haproxy/certs
    state: started
    log_driver: "{{docker_log_driver}}"

- name: reload haproxy when certbot runs
  cron:
    job: docker kill --signal=USR2 haproxy
    minute: 45
    hour: 2
