- name: ensure firewall is open
  become: yes
  with_items: "{{groups['front']}}"
  ufw:
    rule: allow
    from_ip: "{{item}}"
    port: 5000

- name: api image name
  set_fact:
    docker_image_api: "{{docker_registry_name}}/api:{{api_docker_image_tag}}"

- name: pull image
  docker_image:
    force: yes
    name: "{{docker_image_api}}"

- name: create tables
  run_once: yes
  shell: |
    docker run --rm \
      -e SQLALCHEMY_DATABASE_URI="{{api_database_url}}" \
      --entrypoint /entrypoint.sh \
      "{{docker_image_api}}" api_create_tables

- name: create api container
  docker_container:
    image: "{{docker_image_api}}"
    recreate: yes
    network_mode: host
    name: "api{{groups.api.index(inventory_hostname)}}"
    log_driver: "{{docker_log_driver}}"
    state: started
    restart_policy: "{{docker_default_restart_policy}}"
    env:
      JWT_SECRET: "{{api_jwt_secret}}"
      BASE_URL: "{{api_base_url}}"
      SQLALCHEMY_DATABASE_URI: "{{api_database_url}}"
