
# Just a dummy server for now. Using to test haproxy config, etc.

- name: firewall for ui is opened
  become: yes
  with_items: "{{groups['front']}}"
  ufw:
    rule: allow
    from_ip: "{{item}}"
    port: 8000
  notify:
    - reload firewall

- name: pull image
  docker_image:
    name: "{{docker_registry_name}}/ui:{{docker_image_tag_ui}}"

- name: bring up ui server
  docker_container:
    recreate: yes
    network_mode: host
    name: "ui{{groups.ui.index(inventory_hostname)}}"
    image: "{{docker_registry_name}}/ui:{{docker_image_tag_ui}}"
    log_driver: "{{docker_log_driver}}"
    state: started
    restart_policy: "{{docker_default_restart_policy}}"
