version: '3'
services:
  db:
    image: aghost7/pg-dev:10
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
