version: '3'
services:
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
