version: '3'
services:
  api:
    image: python:3.5.2
    command: sleep Infinity
    working_dir: /api
    # volumes:
    #   - $PROJECT_DIR/api:/api
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
